# Generated by Django 5.1.2 on 2024-11-10 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textpad', '0004_documenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='textpad.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('delta_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('INSERT', 'Insert'), ('DELETE', 'Delete'), ('UPDATE', 'Update')], max_length=10)),
                ('position', models.IntegerField()),
                ('length', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='textpad.documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='textpad.snapshot')),
            ],
        ),
    ]
