# Generated by Django 5.1.2 on 2024-11-12 13:18

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textpad', '0005_snapshot_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
